server:
    port: 0

spring:
    application:
        name: account-ws

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
    devtools:
        restart:
            enabled: true






