spring:
  application:
    name: APIConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmadaghazadeh/MicroServiceSampeConfiguration
          clone-on-start: true
          default-label: main

  server:
    port: 8012

