server:
    port: 8082

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
#            discovery:
#                locator:
#                    enabled: true
#                    lower-case-service-id: true
            routes:
                - id: users-path
                  uri: lb://users-ws
                  predicates:
                  - Path=/users-ws/users/isOnline
                  - Method=GET
                  - Header=Authorization, Bearer (.*)
                  filters:
                  - RemoveRequestHeader=Cookie
                  - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka







